name: Scan GitHub followers
on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *" # Every day at 12:00 UTC (07:00 Vietnam time)
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Fetch followers
        run: node --import @swc-node/register/esm-register src/main.ts ghtool list-followers > followers.txt
      - name: Fetch following
        run: node --import @swc-node/register/esm-register src/main.ts ghtool list-following > following.txt
      - name: Commit results
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Another Kai [Jarvis]"
          author_email: 43800313+lyluongthien@users.noreply.github.com
          committer_name: "[Jarvis]"
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          fetch: false
          message: "Update followers and following lists #${{ github.run_number }}"
          add: "./follow*.txt --force"
